# Generated by Django 5.2.3 on 2026-04-27 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('repository', models.CharField(max_length=300)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40)),
                ('commit_message', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical Vulnerability'), ('high', 'High Risk'), ('medium', 'Medium Risk'), ('low', 'Low / No Risk')], max_length=20)),
                ('risk_score', models.FloatField(help_text='0.0 to 1.0')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('running', 'Running')], max_length=20)),
                ('inference_ms', models.IntegerField(help_text='Inference latency in ms')),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('_vulnerabilities_detail', models.TextField(db_column='vulnerabilities_detail', default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scanner.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwe_id', models.CharField(max_length=20)),
                ('cve_id', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('cvss_score', models.FloatField(default=0.0)),
                ('remediation', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_set', to='scanner.pipelinerun')),
            ],
        ),
    ]
